- name: Creating group {{admin_user}}
  group:
    name: "{{admin_user}}"
    state: present

- name: Adding user {{admin_user}} with group {{admin_group}}
  user:
    name: "{{admin_user}}"
    groups: ["{{admin_user}}", "{{admin_group}}"]
    shell: /bin/bash

- name: Resetting admin user password
  shell: "yes '{{admin_password}}' | passwd {{admin_user}}"
