- name: Installing Postgresql
  apt:
    name: ['postgresql', 'python-psycopg2']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Starting Postgresql daemon
  systemd:
   name: 'postgresql'
   state: started
   enabled: yes
   daemon-reload: yes

- name: Delete the Gitea database if exists
  become: true
  become_user: postgres
  become_method: su
  postgresql_db:
    name={{gitea_db}}
    state=absent

- name: Create the Gitea database
  become: true
  become_user: postgres
  become_method: su
  postgresql_db:
    name={{gitea_db}}
    encoding=UTF-8
    lc_collate=en_US.UTF-8
    lc_ctype=en_US.UTF-8
    state=present

- name: Creating Gitea database admin user
  become: true
  become_user: postgres
  become_method: su
  postgresql_user:
    db={{gitea_db}}
    name={{gitea_db_user}}
    password={{gitea_db_password}}
    priv="ALL"
    expires="Jan 31 2040"

